spring.application.name=${SPRING_APPLICATION_NAME:kafka-playground}
server.port=${SERVER_PORT:8081}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.acks=all
spring.kafka.producer.retries=3
